version: '3.1'
services:
  api:
    container_name: 'CRM'
    build: ../CMS_group
    ports:
      - "8080:8080"
    depends_on:
      - database
  database:
    container_name: 'CRM-db'
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crm
      POSTGRES_USER: admin
    volumes:
      - type: volume
        source: api-postgres-volume
        target: /var/lib/postgresql/data
    ports:
      - "6666:5432"
    restart: always
volumes:
  api-postgres-volume:
